### ISSUE TITLE
docs/guides/RouteHistory.md is wrong

### ISSUE THREAD

**Issue by shackra** [tsl/react-router-guard#15]
**Describe the bug**
The documentation is wrong about the use of history.

**To Reproduce**
1. Start a new project and add `react-router-guard v2.1.0`
2. put `import { history } from "react-router-guard"` somewhere in your code
3. do something to call a method of the history object, (like `history.replace`)
4. See error `TypeError: _reactRouterGuard.history.push is not a function`

You can see this bug in action here https://codesandbox.io/s/great-bas-ruwjs?fontsize=14

**Expected behavior**
The code should match what is said in the documentation, but the `history` object exported by react-router-guard is a reference to a class constructor a not an instance..

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser Firefox
 - Version 69.0

**Comment by laptransang** [comment]
Thanks, @shackra for your report I will do a investigate and send you the result after that.

**Comment by laptransang** [comment]
Hi @shackra 

Sorry for long response to you

I just updated a new version 2.2.0 to fix issue missing history in export react-router-guard, you can read the docs for more details, in case if you are using browser hash you must pass your custom history as props history, if you have any confuse please ping me.

Thank you.
